package goAuth

import "errors"

var (
	ErrUnauthorized                       = errors.New("unauthorized")
	ErrInvalidCredentials                 = errors.New("invalid credentials")
	ErrUserNotFound                       = errors.New("user not found")
	ErrLoginRateLimited                   = errors.New("login rate limited")
	ErrRefreshRateLimited                 = errors.New("refresh rate limited")
	ErrAccountExists                      = errors.New("account already exists")
	ErrAccountCreationDisabled            = errors.New("account creation disabled")
	ErrAccountCreationRateLimited         = errors.New("account creation rate limited")
	ErrAccountCreationUnavailable         = errors.New("account creation backend unavailable")
	ErrAccountCreationInvalid             = errors.New("invalid account creation request")
	ErrAccountRoleInvalid                 = errors.New("invalid account role")
	ErrAccountUnverified                  = errors.New("account unverified")
	ErrAccountDisabled                    = errors.New("account disabled")
	ErrAccountLocked                      = errors.New("account locked")
	ErrAccountDeleted                     = errors.New("account deleted")
	ErrAccountVersionNotAdvanced          = errors.New("account version not advanced on status change")
	ErrEmailVerificationDisabled          = errors.New("email verification disabled")
	ErrEmailVerificationInvalid           = errors.New("email verification challenge invalid")
	ErrEmailVerificationRateLimited       = errors.New("email verification rate limited")
	ErrEmailVerificationUnavailable       = errors.New("email verification backend unavailable")
	ErrEmailVerificationAttempts          = errors.New("email verification attempts exceeded")
	ErrPasswordResetDisabled              = errors.New("password reset disabled")
	ErrPasswordResetInvalid               = errors.New("password reset challenge invalid")
	ErrPasswordResetRateLimited           = errors.New("password reset rate limited")
	ErrPasswordResetUnavailable           = errors.New("password reset backend unavailable")
	ErrPasswordResetAttempts              = errors.New("password reset attempts exceeded")
	ErrPasswordPolicy                     = errors.New("password policy violation")
	ErrPasswordReuse                      = errors.New("new password must be different from current password")
	ErrSessionCreationFailed              = errors.New("session creation failed")
	ErrSessionInvalidationFailed          = errors.New("session invalidation failed")
	ErrSessionLimitExceeded               = errors.New("session limit exceeded")
	ErrTenantSessionLimitExceeded         = errors.New("tenant session limit exceeded")
	ErrDeviceBindingRejected              = errors.New("device binding rejected")
	ErrTOTPFeatureDisabled                = errors.New("totp feature disabled")
	ErrTOTPRequired                       = errors.New("totp required")
	ErrTOTPInvalid                        = errors.New("invalid totp code")
	ErrTOTPRateLimited                    = errors.New("totp attempts rate limited")
	ErrTOTPNotConfigured                  = errors.New("totp not configured")
	ErrTOTPUnavailable                    = errors.New("totp backend unavailable")
	ErrMFALoginRequired                   = errors.New("mfa required")
	ErrMFALoginInvalid                    = errors.New("mfa challenge invalid")
	ErrMFALoginExpired                    = errors.New("mfa challenge expired")
	ErrMFALoginAttemptsExceeded           = errors.New("mfa challenge attempts exceeded")
	ErrMFALoginReplay                     = errors.New("mfa challenge replay detected")
	ErrMFALoginUnavailable                = errors.New("mfa challenge backend unavailable")
	ErrBackupCodeInvalid                  = errors.New("invalid backup code")
	ErrBackupCodeRateLimited              = errors.New("backup code rate limited")
	ErrBackupCodeUnavailable              = errors.New("backup code backend unavailable")
	ErrBackupCodesNotConfigured           = errors.New("backup codes not configured")
	ErrBackupCodeRegenerationRequiresTOTP = errors.New("backup code regeneration requires totp verification")
	ErrSessionNotFound                    = errors.New("session not found")
	ErrTokenInvalid                       = errors.New("invalid token")
	ErrTokenClockSkew                     = errors.New("token clock skew exceeded")
	ErrInvalidRouteMode                   = errors.New("invalid route validation mode")
	ErrStrictBackendDown                  = errors.New("strict validation backend unavailable")
	ErrRefreshInvalid                     = errors.New("invalid refresh token")
	ErrRefreshReuse                       = errors.New("refresh token reuse detected")
	ErrPermissionDenied                   = errors.New("permission denied")
	ErrEngineNotReady                     = errors.New("engine not initialized")
	ErrProviderDuplicateIdentifier        = errors.New("provider duplicate identifier")
)
